version: "3.9"
services:
  frontend:
    container_name: frontend_container
    build: ./frontend
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - default

  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - '4000:4000'
    restart: unless-stopped
    networks:
      - default

  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_DB: "fluffyheal_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fluffyheal_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - default

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - default

volumes:
  db-data:
  pgadmin-data:

networks:
  default:
    driver: bridge